services:
  vtn:
    image: vtn
    container_name: vtn
    build:
      context: ./docker-vtn
    # image: jimmyleu76/python-openleadr-nodemon:latest
    # image: 041414866712.dkr.ecr.us-east-2.amazonaws.com/openleadr-vtn:latest
    volumes:
      - /Users/jimmyleu/Development/gismo/openADR:/openleadr-python
      # - ./testvtn.py:/app/app.py
    networks:
      - adrnet
    environment:
      - PYTHONPATH=/openleadr-python:/app
      - VTN_NAME=vtn001
      - PYTHONASYNCIODEBUG=1
      - TIMEZONE=America/Los_Angeles
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres
  ven:
    build:
      context: ./docker-ven
    networks:
      - adrnet
    volumes:
      - /Users/jimmyleu/Development/gismo/openADR:/openleadr-python
      # - ./testven.py:/app/app.py
    environment:
      - VEN_NAME=ven123
      - VTN_URL=http://vtn:8080/OpenADR2/Simple/2.0b
      - RESOURCE_NAME=resource
      - PYTHONPATH=/openleadr-python:/app
      - PYTHONASYNCIODEBUG=1
      - TIMEZONE=America/Los_Angeles
    depends_on:
      - vtn

  postgres:
    build:
      context: ./docker-db
      dockerfile: Dockerfile
    expose:
      - 5432
    networks:
      - adrnet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
networks:
  adrnet:
