version: "3.9"

services:
  vtn:
    platform: linux/amd64
    build:
      context: ./services/openadr/vtn
      args:
        - DEV=true
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-LOCAL} # AWS or LOCAL
      - AGENT_ID=${AGENT_ID:-d5f36f77f24d19a2820538f415b0fd}
      - RESOURCE_ID=${RESOURCE_ID:-resource0}
      - METER_API_URL=${METER_API_URL:-https://ojw7mhmbpd.execute-api.us-east-2.amazonaws.com/dev/meter}
      - DEVICES_API_URL=${DEVICES_API_URL:-https://ojw7mhmbpd.execute-api.us-east-2.amazonaws.com/dev/device}
      - ORDERS_API_URL=${ORDERS_API_URL:-https://ojw7mhmbpd.execute-api.us-east-2.amazonaws.com/dev/order}
      - DISPATCHES_API_URL=${DISPATCHES_API_URL:-https://ojw7mhmbpd.execute-api.us-east-2.amazonaws.com/dev/dispatch}
      - MARKET_INTERVAL_IN_SECONDS=${MARKET_INTERVAL_IN_SECONDS:-20}
    networks:
      - adrnet
    ports:
      - "8080:8080"
    volumes:
      - ./services/openadr/vtn:/app
    command: >
      sh -c "python vtn.py"

  ven:
    platform: linux/amd64
    build:
      context: ./services/openadr/ven
      args:
        - DEV=true
    networks:
      - adrnet
    volumes:
      - ./services/openadr/ven:/app
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-LOCAL} #1 for Ture and 0 for False
      - RESOURCE_ID=${RESOURCE_ID:-resource0}
      - METER_ID=${METER_ID:-meter0}
      - DEVICE_ID=${DEVICE_ID:-2b24017403c418d73b4829372f9c5b43}
      - AGENT_ID=${AGENT_ID:-agent-d5f36f77f24d19a2820538f415b0fd}
      - DEVICE_TYPE=${DEVICE_TYPE:-ES}
      - EMULATED_DEVICE_API_URL=${EMULATED_DEVICE_API_URL:-https://i75blw8jig.execute-api.us-east-2.amazonaws.com/dev/battery_api}
      - 'DEVICE_SETTINGS={"device_brand": "SONNEN_BATTERY", "battery_token": "b51f18cd294592a3777f243287938d", "battery_sn": "40857","flexible":"1","is_using_mock_device":"True"}'
      - MARKET_INTERVAL_IN_SECONDS=${MARKET_INTERVAL_IN_SECONDS:-20}
    command: >
      sh -c "python ven.py"
    ports:
      - "8888:8888"
    depends_on:
      - vtn
networks:
  adrnet:
