version: "3.9"

services:
  vtn:
    platform: linux/amd64
    build:
      context: ./services/vtn
      args:
        - DEV=true
    environment:
      - TIMEZONE=America/Los_Angeles
    networks:
      - adrnet
    ports:
      - "8080:8080"
    volumes:
      - ./services/vtn:/app
    command: >
      sh -c "python vtn.py"

  ven:
    platform: linux/amd64
    build:
      context: ./services/ven
      args:
        - DEV=true
    networks:
      - adrnet
    volumes:
      - ./services/ven:/app
    environment:
      - VEN_NAME=ven123
      - VTN_URL=http://vtn:8080/OpenADR2/Simple/2.0b
      - BATTERY_TOKEN="token123"
      - BATTERY_SERIAL="ba123"
      - DEVICE_ID="device_01"
    # env_file:
    #   - ./services/ven/.env #battery_token
    command: >
      sh -c "python ven.py"

    depends_on:
      - vtn
networks:
  adrnet:
