version: "3.9"

services:
  vtn:
    platform: linux/amd64
    build:
      context: ./services/vtn
      args:
        - DEV=true
    environment:
      - TIMEZONE=America/Los_Angeles
      - SAVE_DATA_URL=https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/openadr_devices
      - GET_VENS_URL=https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/openadr_devices
      - MARKET_PRICES_URL=https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/market_prices
      - PARTICIPATED_VENS_URL=https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/participated_vens
    networks:
      - adrnet
    ports:
      - "8080:8080"
    volumes:
      - ./services/vtn:/app
    command: >
      sh -c "python vtn.py"

  ven:
    platform: linux/amd64
    build:
      context: ./services/ven
      args:
        - DEV=true
    networks:
      - adrnet
    volumes:
      - ./services/ven:/app
    environment:
      - DEV=True
      - VEN_NAME=ven123
      - VTN_URL=http://vtn:8080/OpenADR2/Simple/2.0b
      - MOCK_BATTERY_API_URL=https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/battery_api
      - BATTERY_TOKEN=${BATTERY_TOKEN}
      - BATTERY_SN=${BATTERY_SN}
      - DEVICE_ID=device_01
      - DEVICE_TYPE=SONNEN_BATTERY
      - TIMEZONE=America/Los_Angeles
      - PRICE_THRESHOLD=0.15

    command: >
      sh -c "python ven.py"

    depends_on:
      - vtn
networks:
  adrnet:
