version: "3.9"

services:
  vtn:
    platform: linux/amd64
    build:
      context: ./services/openadr/vtn
      args:
        - DEV=true
    environment:
      - ENV=${ENV:-DEV} # PROD or DEV (PROD: real device, DEV: mock device)
      - AGENT_ID=${AGENT_ID:-agent_0}
      - RESOURCE_ID=${RESOURCE_ID:-resource0}
      - VTN_ID=${VTN_ID:-vtn0}
      - METER_API_URL=${METER_API_URL:-https://yuda2f93e6.execute-api.us-east-2.amazonaws.com/dev/meters}
      - DEVICE_API_URL=${DEVICE_API_URL:-https://yuda2f93e6.execute-api.us-east-2.amazonaws.com/dev/devices}
      - ORDER_PAI_URL=${DEVICE_API_URL:-https://yuda2f93e6.execute-api.us-east-2.amazonaws.com/dev/orders}
      - DISPATCH_API_URL=${DEVICE_API_URL:-https://yuda2f93e6.execute-api.us-east-2.amazonaws.com/dev/dispatches}
      - MARKET_INTERVAL_IN_SECOND=${MARKET_INTERVAL_IN_SECOND:-20}
      - TIMEZONE=${TIMEZONE:-America/Los_Angeles}
    networks:
      - adrnet
    ports:
      - "8080:8080"
    volumes:
      - ./services/openadr/vtn:/app
    command: >
      sh -c "python vtn.py"

  ven:
    platform: linux/amd64
    build:
      context: ./services/openadr/ven
      args:
        - DEV=true
    networks:
      - adrnet
    volumes:
      - ./services/openadr/ven:/app
    environment:
      - ENV=${ENV:-DEV} # PROD or DEV (PROD: real device, DEV: mock device)
      - VEN_ID=${VEN_ID:-ven0}
      - RESOURCE_ID=${RESOURCE_ID:-resource0}
      - METER_ID=${METER_ID:-meter0}
      - DEVICE_ID=${DEVICE_ID:-device0}
      - AGENT_ID=${AGENT_ID:-agent_0}
      - DEVICE_NAME=${DEVICE_NAME:-battery0}
      - VTN_ADDRESS=${VTN_ADDRESS:-vtn}
      - VTN_PORT=${VTN_PORT:-8080}
      - DEVICE_TYPE=${DEVICE_TYPE:-HS}
      - EMULATED_DEVICE_API_URL=${EMULATED_DEVICE_API_URL:-https://5cpljk0hz4.execute-api.us-east-2.amazonaws.com/dev/battery_api}
      - 'DEVICE_SETTINGS={"device_brand": "SONNEN_BATTERY", "battery_token": "12321321qsd", "battery_sn": "66354"}'
      - MARKET_INTERVAL_IN_SECOND=${MARKET_INTERVAL_IN_SECOND:-60}
      - FLEXIBLE=${FLEXIBLE:-True}
    command: >
      sh -c "python ven.py"
    ports:
      - "8000:8000"
    depends_on:
      - vtn
networks:
  adrnet:
