version: "3.9"

services:
  worker:
    platform: linux/amd64
    build:
      context: ./services/devices/worker
      args:
        - DEV=true
    env_file:
      - ./services/devices/worker/.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

      - FIFO_SQS_URL=${FIFO_SQS_URL:-https://sqs.us-east-2.amazonaws.com/041414866712/openadr-NHEC-dev-workers-sqs.fifo}
      - BACKEND_S3_BUCKET_NAME=${BACKEND_S3_BUCKET_NAME:-shared.nhec-dev.tf-state}
      - DYNAMODB_AGENTS_SHARED_REMOTE_STATE_LOCK_TABLE_NAME:${DYNAMODB_AGENTS_SHARED_REMOTE_STATE_LOCK_TABLE_NAME:-openadr-NHEC-dev-agent-shared-tf-state-lock}
      - ECS_CLUSTER_NAME=${ECS_CLUSTER_NAME:-openadr-NHEC-dev-agent-cluster}
      - ENVIRONMENT=${ENVIRONMENT:-LOCAL} # LOCAL,AWS
      - METER_API_URL=${METER_API_URL:-https://fw7sh7bkki.execute-api.us-east-2.amazonaws.com/dev/meter}
      - DEVICES_API_URL=${DEVICES_API_URL:-https://fw7sh7bkki.execute-api.us-east-2.amazonaws.com/dev/device}
      - ORDERS_API_URL=${ORDERS_API_URL:-https://fw7sh7bkki.execute-api.us-east-2.amazonaws.com/dev/order}
      - DISPATCHES_API_URL=${DISPATCHES_API_URL:-https://fw7sh7bkki.execute-api.us-east-2.amazonaws.com/dev/dispatch}
      - EMULATED_DEVICE_API_URL=${EMULATED_DEVICE_API_URL:-https://i75blw8jig.execute-api.us-east-2.amazonaws.com/dev/battery_api}
    volumes:
      - ./services/devices/worker:/app
    command: >
      sh -c "python app.py"
