services:
  vtn:
    container_name: vtn
    build:
      context: ./docker-vtn
    volumes:
      - /Users/jimmyleu/Development/gismo/openADR:/openleadr-python
      # - ./testvtn.py:/app/app.py
    networks:
      - adrnet
    environment:
      - TIMEZONE=America/Los_Angeles
      - DB_USER=mysql
      - DB_PASSWORD=mysql
      - DB_NAME=opendADR
      - DB_HOST=mysql
    ports:
      - 8080:8080
    depends_on:
      - mysql
  # ven:
  #   build:
  #     context: ./docker-ven
  #   networks:
  #     - adrnet
  #   volumes:
  #     - /Users/jimmyleu/Development/gismo/openADR:/openleadr-python
  #   # - ./testven.py:/app/app.py
  #   environment:
  #     - VEN_NAME=ven123
  #     - VTN_URL=http://vtn:8080/OpenADR2/Simple/2.0b
  #     - RESOURCE_NAME=resource
  #     - PYTHONPATH=/openleadr-python:/app
  #     - PYTHONASYNCIODEBUG=1
  #     - TIMEZONE=America/Los_Angeles
  #   depends_on:
  #     - vtn

  mysql:
    build:
      context: ./docker-db
    expose:
      - 3306
    networks:
      - adrnet
    environment:
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
  # postgres:
  #   build:
  #     context: ./docker-db
  #     dockerfile: Dockerfile
  #   expose:
  #     - 5432
  #   networks:
  #     - adrnet
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
networks:
  adrnet:
