version: "3.9"

services:
  vtn:
    platform: linux/amd64
    build:
      context: ./services/vtn
      args:
        - DEV=true
    environment:
      - VTN_ID=${VTN_ID:-vtn0}
      - TIMEZONE=${DETIMEZONEV:-America/Los_Angeles}
      - SAVE_DATA_URL=${SAVE_DATA_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/openadr_devices}
      - GET_VENS_URL=${GET_VENS_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/openadr_devices}
      - MARKET_PRICES_URL=${GET_VENS_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/market_prices}
      - PARTICIPATED_VENS_URL=${GET_VENS_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/participated_vens}
      - INTERVAL_OF_FETCHING_MARKET_PRICE_INSECOND=${INTERVAL_OF_FETCHING_MARKET_PRICE_INSECOND:-20}
    networks:
      - adrnet
    ports:
      - "8080:8080"
    volumes:
      - ./services/vtn:/app
    command: >
      sh -c "python vtn.py"

  ven:
    platform: linux/amd64
    build:
      context: ./services/ven
      args:
        - DEV=true
    networks:
      - adrnet
    volumes:
      - ./services/ven:/app
    environment:
      - MOCK=${MOCK:-"False"}
      - VEN_ID=${VEN_ID:-ven0}
      - VTN_URL=${VTN_URL:-http://vtn:8080/OpenADR2/Simple/2.0b}
      - MOCK_BATTERY_API_URL=${MOCK_BATTERY_API_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/battery_api}
      - BATTERY_TOKEN=${BATTERY_TOKEN:-12321321qsd}
      - BATTERY_SN=${BATTERY_SN:-66354}
      - DEVICE_ID=${DEVICE_ID:-device_0}
      - DEVICE_TYPE=${DEVICE_TYPE:-SONNEN_BATTERY}
      - TIMEZONE=${TIMEZONE:-America/Los_Angeles}
      - PRICE_THRESHOLD=${PRICE_THRESHOLD:-0.15}
      - INTERVAL_OF_FETCHING_DEVICE_DATA_INSECOND=${INTERVAL_OF_FETCHING_DEVICE_DATA_INSECOND:-10}
      - REPORT_DURATION_INSECOND=${REPORT_DURATION_INSECOND:-3600} # report_duration: The time span that can be provided in this report.
      - REPORT_SPECIFIER_ID=${REPORT_SPECIFIER_ID:-SONNEN_BATTERY}
    command: >
      sh -c "python ven.py"

    depends_on:
      - vtn
networks:
  adrnet:
