version: "3.7"

services:
  worker:
    build:
      context: .
    # image: hashicorp/terraform:1.3.6
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - HEALTH_CHEKC_PORT=${HEALTH_CHEKC_PORT:-8070}
      - FIFO_SQS_URL=${FIFO_SQS_URL:-https://sqs.us-east-2.amazonaws.com/041414866712/openadr_workers_sqs.fifo}
      - FIFO_DLQ_URL=${FIFO_DLQ_URL:-https://sqs.us-east-2.amazonaws.com/041414866712/openadr_workers_dlq.fifo}
      - AWS_REGION=${AWS_REGION:-us-east-2}
      - DYNAMODB_AGENTS_SHARED_REMOTE_STATE_LOCK_TABLE_NAME=${DYNAMODB_AGENTS_SHARED_REMOTE_STATE_LOCK_TABLE_NAME:-openadr-agent-shared-tf-state-lock}
      - BACKEND_S3_BUCKET_NAME=${BACKEND_S3_BUCKET_NAME:-openadr-agents-state}
