services:
  vtn:
    # container_name: vtn
    build:
      context: .

    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=opendADR
      - DB_HOST=postgres
    ports:
      - 8080:8080
