version: "3.9"

services:
  worker:
    platform: linux/amd64
    build:
      context: ./worker
      args:
        - DEV=true
    environment:
      - ENV=${ENV:-DEV} # PROD or DEV (PROD: real device, DEV: mock device)
      # ECS cluster params that had beed pre-configed in the main system
      - ECS_CLUSTER_NAME=${ECS_CLUSTER_NAME:-openadr-dev-agents-cluster}
      - SQS_URL=${SQS_URL:-https://sqs.us-east-2.amazonaws.com/041414866712/openadr_workers_sqs}
      - PRIVATE_SG_NAME="public-bastion-sg-20230310035653545700000004"
      - ECS_TASK_EXECUTION_ROLE_NAME="openadr-task-exec-role"
      - ECS_TASK_ROLE_NAME="openadr-vtn-task"
      - PRIVATE_VPC_ID="vpc-05e9f374f4a835e2b"
      - CLOUDWATCH_NAME="openadr-ecs-agent"
      - DYNAMODB_TABLE_NAME="openadr-dev-agents"
      - S3_BUCKET_NAME="openadr-agents-state"
      - APP_IMAGE_VTN=${APP_IMAGE_VTN:-041414866712.dkr.ecr.us-east-2.amazonaws.com/vtn:latest},
      - APP_IMAGE_VEN=${APP_IMAGE_VTN:-041414866712.dkr.ecr.us-east-2.amazonaws.com/ven:latest} ,

      # AWS config
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

      # ECS task definitions include containers, a vtn and multiple vens. Each VEN represents a device
      # This params
      # The vtn params

      - SAVE_DATA_URL=${SAVE_DATA_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/openadr_devices}
      - GET_VENS_URL=${GET_VENS_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/openadr_devices}
      - MARKET_PRICES_URL=${GET_VENS_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/market_prices}
      - PARTICIPATED_VENS_URL=${GET_VENS_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/participated_vens}
      # The ven params
      - MOCK_DEVICES_API_URL=${MOCK_DEVICES_API_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/battery_api}

      - VTN_ADDRESS=${VTN_ADDRESS:-vtn}
      - VTN_PORT=${VTN_PORT:-8080}

    volumes:
      - ./devices_admin/controller
    # command: >
    #   sh -c "python app.py"
