version: "3.9"

services:
  worker:
    platform: linux/amd64
    build:
      context: ./worker
      args:
        - DEV=true
    env_file:
      - .env

    volumes:
      - ./devices_admin/controller
    # command: >
    #   sh -c "python app.py"
