version: "3.9"

services:
  worker:
    platform: linux/amd64
    build:
      context: ./worker
      args:
        - DEV=true
    env_file:
      - ./worker/.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./worker:/app
    command: >
      sh -c "python app.py"

  cli:
    platform: linux/amd64
    build:
      context: ./cli
      args:
        - DEV=true
    env_file:
      - ./worker/.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    volumes:
      - ./worker:/app
    command: >
      sh -c "python app.py"
