# The backend of this ECS services


# Terraform remote backend, -backend-config=backend.hcl
# This remote backend is used to store the state file in S3 bucket
# The backend variables are store in backend.hcl and generated by python script

# include the following content:
# bucket         = "<your s3 state bucket>"
# key            = "<your state key>"
# region         = "<your aws region>"
# encrypt        = true
# dynamodb_table = "<your dynamodb table>" # Please create a "LockID" as a primary key

terraform {
  backend "s3" {}
}


# Provider Block
provider "aws" {
  region  = var.aws_region
  profile = "default"
}


terraform {
  required_version = ">= 1.0" # which means any version equal & above 0.14 like 0.15, 0.16 etc and < 1.xx
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }
}

