version: "3.9"

services:
  ven:
    platform: linux/amd64
    image: 041414866712.dkr.ecr.us-east-2.amazonaws.com/ven:latest
    volumes:
      - ./services/ven:/app
    environment:
      - VEN_NAME=ven123
      - VTN_URL=http://vtn:8080/OpenADR2/Simple/2.0b
      - BATTERY_TOKEN=${BATTERY_TOKEN}
      - BATTERY_SN=66352
      - DEVICE_ID=device_01
      - DEVICE_TYPE=SONNEN_BATTERY
      - TIMEZONE=America/Los_Angeles
      - PRICE_THRESHOLD=0.15

    command: >
      sh -c "python ven.py"
