version: "3.9"

services:
  vtn:
    platform: linux/amd64
    build:
      context: ./vtn
      args:
        - DEV=true
    environment:
      - ENV=${ENV:-DEV} # PROD or DEV (PROD: real device, DEV: mock device)
      - AGENT_ID=${AGENT_ID:-agent_0}
      - RESOURCE_ID=${RESOURCE_ID:-resource0}
      - VTN_ID=${VTN_ID:-vtn0}
      - METER_API_URL=${METER_API_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/openadr_devices}
      - DEVICE_API_URL=${DEVICE_API_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/openadr_devices}
      - ORDER_PAI_URL=${DEVICE_API_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/market_prices}
      - DISPATCH_API_URL=${DEVICE_API_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/participated_vens}
      - MARKET_INTERVAL_IN_SECOND=${MARKET_INTERVAL_IN_SECOND:-20}
    networks:
      - adrnet
    ports:
      - "8080:8080"
    volumes:
      - ./vtn:/app
    command: >
      sh -c "python vtn.py"

  ven:
    platform: linux/amd64
    build:
      context: ./ven
      args:
        - DEV=true
    networks:
      - adrnet
    volumes:
      - ./ven:/app
    environment:
      - ENV=${ENV:-DEV} # PROD or DEV (PROD: real device, DEV: mock device)
      - VEN_ID=${VEN_ID:-ven0}
      - RESOURCE_ID=${RESOURCE_ID:-resource0}
      - METER_ID=${METER_ID:-meter0}
      - DEVICE_ID=${DEVICE_ID:-device0}
      - AGENT_ID=${AGENT_ID:-agent_0}
      - DEVICE_NAME=${DEVICE_NAME:-battery0}
      - VTN_ADDRESS=${VTN_ADDRESS:-vtn}
      - VTN_PORT=${VTN_PORT:-8080}
      - DEVICE_TYPE=${DEVICE_TYPE:-HS}
      - EMULATED_DEVICE_API_URL=${EMULATED_DEVICE_API_URL:-https://l19grkzsyk.execute-api.us-east-2.amazonaws.com/dev/battery_api}
      - 'DEVICE_SETTINGS={"device_brand": "SONNEN_BATTERY", "battery_token": "12321321qsd", "battery_sn": "66354"}'
      - MARKET_INTERVAL_IN_SECOND=${MARKET_INTERVAL_IN_SECOND:-60}
      - BIDING_PRICE_THRESHOLD=${PRICE_THRESHOLD:-0.15}
    command: >
      sh -c "python ven.py"

    depends_on:
      - vtn
networks:
  adrnet:
